version: "3.9"

services:
  keycloak:
    build:
      context: keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passwd
    command:
      - start-dev

